spring:
  # JPA 설정
  jpa:
    hibernate:
      ddlAuto: create # ddl-auto 와 동일

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: false # 실제 배포 서버 false 로 설정해야 함!

  # 정적 자원 경로 설정 (CSS, JS, 이미지) - static 경로로 설정
  web:
    resources:
      staticLocations: classpath:/static/ # static-locations 와 동일

  # 타임 리프 설정
  thymeleaf:
    cache: true
    prefix: classpath:/templates/

  # 파일 업로드 경로 설정
  file:
    upload:
      path: /home/ubuntu/uploads
      url: /upload/